# Generated by Django 4.0.4 on 2022-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plucking_date', models.DateTimeField()),
                ('crop_data', models.CharField(choices=[('crop_today', (('greentea', 'Greentea'), ('purpletea', 'Purpletea')))], default=False, max_length=50)),
                ('crop_today', models.IntegerField()),
                ('crop_todate', models.IntegerField(blank=True, null=True)),
                ('plucker_numbers', models.IntegerField()),
                ('plucking_average', models.IntegerField(blank=True, null=True)),
                ('total_crop', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.CharField(max_length=20)),
                ('fertilizer_applied', models.DateTimeField()),
                ('fertilizer_amt', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fertilizer_labour', models.IntegerField()),
                ('fertilizer_cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Kandojobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruning_done', models.DateTimeField()),
                ('pruned_block_No', models.IntegerField()),
                ('pruned_bushes', models.IntegerField()),
                ('pruning_rate', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('pruning_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weeding_done', models.DateTimeField(default=None)),
                ('chemical_name', models.CharField(default=None, max_length=100)),
                ('block_No', models.IntegerField(default=None)),
                ('cost_per_lit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weeding_chem_amt', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weeding_labour_number', models.IntegerField(default=None)),
                ('weeding_labour_rate', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('weeding_labour', models.IntegerField(default=None)),
                ('weeding_cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milking_done', models.DateTimeField()),
                ('milk_today', models.DecimalField(decimal_places=2, max_digits=8)),
                ('milk_todate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cows_milked', models.IntegerField()),
                ('cow_numbers', models.IntegerField()),
                ('milking_average', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_milk', models.DecimalField(decimal_places=2, max_digits=8)),
                ('calf_down', models.DateTimeField()),
                ('calf_numbers', models.IntegerField(blank=True)),
                ('vet_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('Total_vet_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
            ],
        ),
    ]
