# Generated by Django 4.0.4 on 2022-08-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk',
            name='calf_down',
            field=models.DateTimeField(),
        ),
    ]
