# Generated by Django 4.0.4 on 2022-07-31 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0002_rename_crop_crop_crop_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='Plucking_date',
            new_name='plucking_date',
        ),
    ]
