# Generated by Django 4.0.4 on 2022-07-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0003_rename_plucking_date_crop_plucking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='plucking_date',
            field=models.DateTimeField(),
        ),
    ]
