# Generated by Django 4.0.4 on 2022-08-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogoon', '0004_alter_crop_plucking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_todate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='plucking_average',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='total_crop',
            field=models.IntegerField(null=True),
        ),
    ]
